# -*- coding: utf-8 -*-
"""Yolov7_borewell_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H23QXcqpMznApcPNvcX80wp6ctf3eCIz

# YOLOv7 for  detecting borewells
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from matplotlib import pyplot as plt
import cv2 as cv

# Commented out IPython magic to ensure Python compatibility.
# %cd ../
!mkdir tmp_
# %cd tmp_

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/WongKinYiu/yolov7 # clone repo
# %cd yolov7
# Install dependencies
# %pip install -qr requirements.txt  # install dependencies

# %cd ../
import torch
#print("Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})"

# Commented out IPython magic to ensure Python compatibility.
# %cp -r /content/drive/MyDrive/Borewell_yolov7.v1i.yolov8 /tmp_

import yaml

data_yaml = dict(
    train = '/content/drive/MyDrive/Borewell_yolov7.v1i.yolov8/train',
    val = '/content/drive/MyDrive/Borewell_yolov7.v1i.yolov8/valid',
    nc = 3,
    names = ['completly_close_safe', 'open_danger', 'unsafe_warning']
)

# Note that I am creating the file in the yolov5/data/ directory.
with open('data.yaml', 'w') as outfile:
    yaml.dump(data_yaml, outfile, default_flow_style=True)

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov7

!wandb disabled
!python train.py --img 416 --batch 16 --epochs 50 --data ../data.yaml  --weights 'yolov7.pt'

img = cv.imread("runs/train/exp/results.png")
plt.figure(figsize=(15, 15))
plt.imshow(img)

"""VALIDATION OUTPUT"""

img = cv.imread("runs/train/exp/test_batch2_pred.jpg")
plt.figure(figsize=(15, 15))
plt.imshow(img)

"""Test the model"""

!python detect.py --source /content/drive/MyDrive/Borewell_yolov7.v1i.yolov8/test/images/borewellrescuemixed1023_jpg.rf.bac94fc27d1a91292d5eff29cf4a87de.jpg --weights runs/train/exp/weights/best.pt

img = cv.imread("runs/detect/exp2/borewellrescuemixed1023_jpg.rf.bac94fc27d1a91292d5eff29cf4a87de.jpg")
plt.imshow(img)